pipeline {
    agent {
        docker {
            image 'node:10-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'rm -rf build'
                sh 'npm install'
            }
        }

        stage('deliver for dev'){
            when{
                branch 'dev'
            }
            steps {
                sh 'echo "dev"'
            }
        }

        stage('deliver for master'){
            when {
                branch 'master'
            }
            steps {
                sh 'echo "master"'
            }
        }
    }
}
